spring:
  application:
    name: acrdemo
  main:
    banner-mode: "off"
    log-startup-info: false
  datasource:
    url: jdbc:postgresql://first-cluster-34286.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb
    username: ${DB_USERNAME:coderkamlesh}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # CockroachDB serverless wake-up delay handle karne ke liye (5s)
      connection-timeout: 5000
      # Lambda context me connection pool chhota rakhna hai
      maximum-pool-size: 2
      minimum-idle: 0
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: LambdaHikariPool

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      show-details: never

logging:
  level:
    root: WARN
    org.springframework.boot: WARN
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    com.example.acrdemo: INFO