spring:
  application:
    name: acrdemo
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true          # Enables /actuator/health/liveness & /readiness
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      show-details: always     # Optional: for debugging
server:
  port: 8080                   # Match probe port

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO

